name: Docker Image Security Scan

on:
  # workflow_run:
  #   workflows: ["Build and Push to ACR"]
  #   types:
  #     - completed
    workflow_dispatch:
     inputs:
      action:
        description: 'Select action (yes or no)'
        required: true
        default: 'yes'


jobs:
  scan:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          az acr login --name infraacr1952

      # - name: Build Docker image
      #   run: docker build -t react-portfolio-app:v1 ./application

      - name: Run Trivy vulnerability scanner
        id: trivy
        uses: aquasecurity/trivy-action@0.14.0
        with:
          image-ref: 'infraacr1952.azurecr.io/react-portfolio-app:v1'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          output: trivy-report.txt

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./application 
          args: >
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.host.url=https://sonarcloud.io            

      # - name: Send Email Alert (via SMTP - iCloud example)
      #   if: steps.check_vulns.outputs.found == 'true'
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.mail.me.com
      #     server_port: 587
      #     username: ${{ secrets.ICLOUD_EMAIL }}
      #     password: ${{ secrets.ICLOUD_APP_PASSWORD }}
      #     subject: "ðŸš¨ Security Alert: Vulnerabilities in Docker Image"
      #     to: "your_email@icloud.com"
      #     from: "CI Pipeline <${{ secrets.ICLOUD_EMAIL }}>"
      #     body: |
      #       Vulnerabilities were found in the latest Docker build.
      #       See attached Trivy report.
      #     attachments: trivy-report.txt
